### ISSUE TITLE
MauiAppBuilder does not contain a definition for AddAudio()...

### ISSUE THREAD

**Issue by guyemup** [jfversluis/Plugin.Maui.Audio#113]
I created a brand new MAUI Hybrid .NET 8 project. I got only this NuGet package and I only added the using and the AddAudio() line in MauiProgram.cs but I'm receiving the error, "MauiAppBuilder does not contain a definition for AddAudio()...". What am I missing?

``
using Microsoft.Extensions.Logging;
using Plugin.Maui.Audio;

namespace MauiAudioTest1
{
    public static class MauiProgram
    {
        public static MauiApp CreateMauiApp()
        {
            var builder = MauiApp.CreateBuilder();
            builder
                .UseMauiApp<App>()
                .AddAudio()
                .ConfigureFonts(fonts =>
                {
                    fonts.AddFont("OpenSans-Regular.ttf", "OpenSansRegular");
                });

            builder.Services.AddMauiBlazorWebView();

#if DEBUG
    		builder.Services.AddBlazorWebViewDeveloperTools();
    		builder.Logging.AddDebug();
#endif

            return builder.Build();
        }
    }
}

**Comment by bijington** [comment]
What version are you using?

**Comment by bijington** [comment]
AddAudio only exists in v3 which is in preview. Perhaps we needed to highlight this in the readme

**Comment by guyemup** [comment]
@bijington , thank you for the clarification. I updated to the latest preview version (was using 2.1.0) and that resolved it. I think adding that to the readme would be helpful as it was not clear to me.
