### ISSUE TITLE
Investigate how playing behaves when other audio is playing on device

### ISSUE THREAD

**Issue by jfversluis** [jfversluis/Plugin.Maui.Audio#12]
And determine what we want to do with that.

* Give people options to interrupt already running audio?
* Always stop audio for our audio?
* Play our audio together with the already running audio?
* Other options?

**Comment by bijington** [comment]
This has been solved on iOS at least with https://github.com/jfversluis/Plugin.Maui.Audio/pull/101

**Comment by jfversluis** [comment]
Yeah I think I had iOS in mind mostly. For other platforms lets see if people open issues and deal with it then.
