### ISSUE TITLE
Dependency on Microsoft.Maui.Controls

### ISSUE THREAD

**Issue by JeroenBer** [jfversluis/Plugin.Maui.Audio#123]
The version 2.1.0 had no real dependencies. Since Audio 3.0.0 package there is a dependency on Microsoft.Maui.Controls. 
Out .NET application doesn't have any dependencies on Maui, and we would like to keep it so. Why would there be a need for a dependency on Maui ?

**Comment by bijington** [comment]
Good spot! This really shouldn't be the case. I have opened a PR that removes the dependency

**Comment by JeroenBer** [comment]
Thanks, the dependency is a problem since it includes other stuff which includes dependencies on certain versions of Google which broke our build with a package downgrade.

However just removing the reference now gives warnings when building the Audio project in VS:
`warning MA002: Starting with .NET 8, setting  <UseMaui>true</UseMaui>  does not automatically include NuGet package references in your project.  Update your project by including this item:  <PackageReference Include="Microsoft.Maui.Controls" Version="8.0.61" />.  You can skip this warning by setting  <SkipValidateMauiImplicitPackageReferences>true</SkipValidateMauiImplicitPackageReferences>  in your project `file.`
`

I think a better approach would be to set UseMaui to false and include a reference to nuget package:
<PackageReference Include="Microsoft.Maui.Essentials" Version="8.0.80" />

**Comment by bijington** [comment]
Oh that is a good point! @jfversluis do you think we should remove `UseMaui` from the project file for the main project like the toolkit now does?

**Comment by jfversluis** [comment]
I don't see why not. Let's do it!
