### ISSUE TITLE
Monitor Mic Level

### ISSUE THREAD

**Issue by bryanp-ramosoil** [jfversluis/Plugin.Maui.Audio#128]
Enhancement

Have you looked into a real time audio input level?
The thought behind it is activiating recording when the input reaches a set threshold.

See this example
https://github.com/swharden/Csharp-Data-Visualization/blob/main/dev/old/2021-07-03-console-microphone/Program.cs

**Comment by bryanp-ramosoil** [comment]
Sorry for the noob question. This is probably best added to the Community Toolkit

**Comment by bijington** [comment]
I think someone has asked for a similar concept but for stopping recordings once the mic input level drops below a threshold. I like the idea but not sure how we would achieve it just yet

**Comment by bryanp-ramosoil** [comment]
For android I've seen examples like this ...
This was an old post so I'm not sure if this code would work. 

mRecorder = new MediaRecorder();
mRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
mRecorder.setOutputFormat(MediaRecorder.OutputFormat.THREE_GPP);
mRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AMR_NB);
mRecorder.setOutputFile("/dev/null"); 
mRecorder.prepare();
mRecorder.start();

public double getAmplitude() {
            if (mRecorder != null)
                    return  (mRecorder.getMaxAmplitude());
            else
                    return 0;

}

powerDb = 20 * log10(getAmplitude() / referenceAmp);

I'm looking to see what's needed for iOS as well.
