### ISSUE TITLE
Package does not support net6.0

### ISSUE THREAD

**Issue by bijington** [jfversluis/Plugin.Maui.Audio#24]
If a .NET MAUI project is being unit tested it will mostly likely target `net6.0`. If this is targeted then the package cannot be added as it does not support `net6.0`.

**Comment by matthewclendening** [comment]
Yes, this is a problem if you utilized the technique in Gerald's nice video at https://www.youtube.com/watch?v=C9vIDLQwc7M. One workaround is to use the preprocessor:
`
#if !NET6_0
    // do audio stuff
#endif
`

However, this is annoying. I can't imagine it would be hard to stub in a do nothing implementation in AudioPlayer.shared.cs for just the NET6.0 case. After all, I don't think we ever expect anything to happen sound-wise if we are targeting NET6.0.

**Comment by jfversluis** [comment]
This is closed by #28, right? :)

**Comment by bijington** [comment]
> This is closed by #28, right? :)

Oh yeah good spot!

**Comment by matthewclendening** [comment]
Oops - I didn't realize that creating a PR created a ticket also - or
perhaps I referenced something incorrectly....
