### ISSUE TITLE
Play() should be declared as async as it is its default behavior.

### ISSUE THREAD

**Issue by pierre01** [jfversluis/Plugin.Maui.Audio#25]
When Play() is invoked it runs asynchronously. 
I like it but it might be nice to declare it as an asynchronous function so it can be awaited.

https://user-images.githubusercontent.com/2603287/188267318-574c7492-06ab-46c0-9c71-ee3702cbf2c2.mp4

**Comment by pierre01** [comment]
From the Video above.
_payerBeep.Play() method is async as you can see the soundwave running in parallel to the animations in the video. 
Although I can't make the function call, part of the WhenAll statement. 
On the other hand, TextToSpeech acts erratically in this condition (the reason why I commented it out).
Plugin.Maui.Audio deserves to be in the Microsoft.Maui.Media. (more than TextToSpeech for sure)

Sample can be found at:
https://github.com/pierre01/TimerFaceMockup

**Comment by bijington** [comment]
I think we could quite easily wrap the current player up inside an async wrapper class. I think we would end up with something like (written entirely here so will likely need some work):

```csharp
public class AsyncAudioPlayer
{
    private readonly IAudioPlayer audioPlayer;

    public Task PlayAsync(CancellationToken cancellationToken)
    {
        var taskCompletionSource = new TaskCompletionSource<bool>();

        try
        {
            audioPlayer.PlaybackEnded += (o, e) => taskCompletionSource.SetResult(true);

            return taskCompletionSource.Task;
        }
        catch (OperationCanceledException oce)
        {
        }
    }
}
```

**Comment by ccscherer** [comment]
I did something like this:

var audioPlayer1 = audioManager.CreatePlayer(await FileSystem.OpenAppPackageFileAsync("sound1.mp3"));
audioPlayer1.Play();
await Task.Delay(Convert.ToInt32(audioPlayer1.Duration)); 

await Task.Delay(3000);  // time between the sounds

var audioPlayer2 = audioManager.CreatePlayer(await FileSystem.OpenAppPackageFileAsync("sound2.mp3"));
audioPlayer2.Play();
await Task.Delay(Convert.ToInt32(audioPlayer2.Duration)); 

I know that is not the best code, but it works for me!
