### ISSUE TITLE
您好，我想问一下这个包能在安卓应用上使用吗，因为我这里使用报了些错误，麻烦给些提示。先谢谢您

### ISSUE THREAD

**Issue by changhengyu** [jfversluis/Plugin.Maui.Audio#31]
![Uploading I5HZB$)Y3B%X$8U[D4Y)XHK(1).png…]()

**Comment by changhengyu** [comment]
您好，我想问一下这个包能在安卓应用上使用吗，因为我这里使用报了些错误，麻烦给些提示。先谢谢您

**Comment by changhengyu** [comment]
![Uploading I5HZB$)Y3B%X$8U[D4Y)XHK(1).png…]()

**Comment by jfversluis** [comment]
As much as I want to be inclusive and supportive of everyone I’m afraid I am not proficient in this language. If you want us to help please communicate in English. Thanks!
