### ISSUE TITLE
AudioManager.Current.CreatePlayer only works with stream, not filename

### ISSUE THREAD

**Issue by cdavidyoung** [jfversluis/Plugin.Maui.Audio#32]
I first tried to use audioPath directly but it would not work.  It does work with the stream.  So I am good but the overloaded version that takes filename seems to have a problem.

         IAudioPlayer_audioPlayer = AudioManager.Current.CreatePlayer(audioPath); // does not work
        _audioPlayer.Play();

         var stream = File.OpenRead(audioPath);
        IAudioPlayer_audioPlayer = AudioManager.Current.CreatePlayer(stream); // works
        _audioPlayer.Play();

**Comment by jfversluis** [comment]
Could you elaborate a bit more on your code?

What was the actual value of `audioPath`? On what platform were you running that?

**Comment by cdavidyoung** [comment]
"C:\\Users\\charl\\AppData\\Local\\Packages\\325FF80D-9423-4151-9145-1460A8A5A391_9zz4h110yvjzm\\LocalState\\Audio38.mp3"

I was running on Windows at the time but it behaves the same on Android and Mac.  Here is a part of the class that works:

   public class AudioService
   {
      IAudioPlayer _audioPlayer = null;

      // private readonly AudioRecorderService _audioRecorderService = new AudioRecorderService();
      Timer myTimer = null;
      DateTime startTime;
      public TimeSpan ts = TimeSpan.Zero;
      public event EventHandler FinishedPlaying = null;
      .
      .
      .
      public void playAudio(string audioPath)
      {
         if (_audioPlayer != null)
            _audioPlayer.Stop();

         // if (_audioRecorderService.IsRecording)
         //    await _audioRecorderService.StopRecording();

         myTimer = new Timer();
         myTimer.Interval = 100;
         myTimer.Elapsed += t_Tick;
         startTime = DateTime.Now;
         myTimer.Start();

         var stream = File.OpenRead(audioPath);
        _audioPlayer = AudioManager.Current.CreatePlayer(stream);
        _audioPlayer.PlaybackEnded += (object sender, EventArgs e) =>
           {
              _audioPlayer = null;
              myTimer?.Stop();
              Console.WriteLine($"playAudio FinishedPlaying: {ts.ToString("s'.'f''")}");
              if (this.FinishedPlaying != null)
              {
                 this.FinishedPlaying(sender, e);
                 this.FinishedPlaying = null;
              }
           };
        _audioPlayer.Play();
      }

**Comment by jfversluis** [comment]
Yeah so looking at the code [here](https://github.com/jfversluis/Plugin.Maui.Audio/blob/main/src/Plugin.Maui.Audio/AudioPlayer.windows.cs#L60) we load it from the application assets. So it really needs to be in there as a resource for it to work.

We might need to clarify on that.

**Comment by cdavidyoung** [comment]
Sorry, but I just saw your question.  As far as I am concerned, the fact that it works with a Stream is all I need.  However, the overloaded version to work with a filename (and complete filepath) would be one extra line of code.  I would be happy to check into this.  I am just not sure of the mechanics of making the change and testing.  Do I need to clone the repository and test it locally first?  Sorry for the newby question.  I am accustomed to building apps, not NuGet packages.

**Comment by bijington** [comment]
I think this ties into our discussion of having an AudioSource parameter instead of a string so that we could easily work out where the source is coming from. I don't believe we look on disk with the string approach but we probably could without too much effort

**Comment by Grasscropper** [comment]
Hello,

It seems to me that there is an issue in the constructor of the android version of AudioPlayer when it comes to the overload with string fileName as parameter. There MediaPlayer is instantiated with "Looping = Loop" where Loop's get method refers to "player.Looping". Since player is not yet set (the instantiating MediaPlayer is about to be set to player) it will always fail.  Can you confirm is this is indeed an issue?

```
    public bool Loop
    {
        get => player.Looping;
        set => player.Looping = value;
    }

    public bool CanSeek => true;

    internal AudioPlayer(Stream audioStream)
    {
        player = new MediaPlayer();
        player.Completion += OnPlaybackEnded;

        if (OperatingSystem.IsAndroidVersionAtLeast(23))
        {
            stream = new MemoryStream();
            audioStream.CopyTo(stream);
            var mediaDataSource = new StreamMediaDataSource(stream);
            player.SetDataSource(mediaDataSource);
            player.Prepare();
        }
        else
        {
            PreparePlayerLegacy(audioStream);
        }
    }

    internal AudioPlayer(string fileName)
    {
        player = new MediaPlayer() { Looping = Loop };
        player.Completion += OnPlaybackEnded;

        AssetFileDescriptor afd = Android.App.Application.Context.Assets?.OpenFd(fileName)
            ?? throw new FailedToLoadAudioException("Unable to create AssetFileDescriptor.");

        player.SetDataSource(afd.FileDescriptor, afd.StartOffset, afd.Length);

        player.Prepare();
    }
```
