### ISSUE TITLE
Audio stops sporadically on iOS

### ISSUE THREAD

**Issue by jnthngdbt** [jfversluis/Plugin.Maui.Audio#43]
Hey,

It works great on Windows 11 (thanks for the plugin and the sample app!). 

But when running on an iPhone 14 with iOS 16.1.1, the audio will start but will stop after a few seconds in a non-systematic way.

I develop in Visual Studio 2022 17.4.4.

Thanks,

Jonathan

**Comment by jnthngdbt** [comment]
Precision: I am having this issue with the sample app https://github.com/jfversluis/MauiPluginAudioSample.

I tested with the sample app in this repo and it seems to work fine.

**Comment by bijington** [comment]
If it works in the sample app I would suggest checking what the differences are between that and the one you have referenced.

From a quick look I can see that the `player` in the broken sample is only kept in scope of the button click event handler. Perhaps you could try holding a reference to it at the class level and see if that solves your issue?

**Comment by jnthngdbt** [comment]
Thanks for your response, that did it!

**Comment by jfversluis** [comment]
Looks like this is done then!
