### ISSUE TITLE
How can i stop previous audioPlayer before creating new one ?

### ISSUE THREAD

**Issue by comm-amir-david** [jfversluis/Plugin.Maui.Audio#45]
i need two function one is to stop previous audioPlayer before creating new one and playing it.
other is to finish current playing audio then create a new one and play it.

the problem that there is no load option inside AudioPlayer and i must create new instant every time i need to play a audio ??

**Comment by bijington** [comment]
> the problem that there is no load option inside AudioPlayer and i must create new instant every time i need to play a audio ??

This is by design. AudioPlayer is immutable so you can't load in different audio files. You can create as many players as you like and start/stop then when you like

**Comment by comm-amir-david** [comment]
this will not create a memory leak ?

**Comment by bijington** [comment]
Having multiple players created will consume more memory but you shouldn't experience any leaking so long as you don't continue to hold a reference to them once you have finished. They implement `IDisposable` so you have the power to tidy them up

**Comment by jfversluis** [comment]
No response anymore so assuming this is handled. Thanks!
