### ISSUE TITLE
App crashes on low android level **Java.IO.IOException:** 'Prepare failed.: status=0x1'

### ISSUE THREAD

**Issue by ertandk** [jfversluis/Plugin.Maui.Audio#47]
Hello, I managed to play the sound by watching the video on youtube (android 10.11), but,
On an old device (android 6.0.1) etc. It directly causes my application to crash.
Its output is;
```
[MediaPlayer] error (1, -2147483648)
**Java.IO.IOException:** 'Prepare failed.: status=0x1'
[mono-rt] [ERROR] FATAL UNHANDLED EXCEPTION: Java.IO.IOException: Prepare failed.: status=0x1
[mono-rt] at Java.Interop.JniEnvironment.InstanceMethods.CallVoidMethod(JniObjectReference instance, JniMethodInfo method, JniArgumentValue* args) in /Users/runner/work/1/s/xamarin-android/external/Java.Interop/src/ java.Interop/obj/Release/net7.0/JniEnvironment.g.cs:line 11884
[mono-rt] at Java.Interop.JniPeerMembers.JniInstanceMethods.InvokeVirtualVoidMethod(String encodedMember, IJavaPeerable self, JniArgumentValue* parameters) in /Users/runner/work/1/s/xamarin-android/external/Java/Interop Java.Interop/Java.Interop/JniPeerMembers.JniInstanceMethods_Invoke.cs:line 66
[mono-rt] at Android.Media.MediaPlayer.Prepare() in /Users/runner/work/1/s/xamarin-android/src/Mono.Android/obj/Release/net7.0/android-33/mcw /Android.Media.MediaPlayer.cs:line 3748
[mono-rt] at Plugin.Maui.Audio.AudioPlayer..ctor(Stream audioStream)
[mono-rt] at Plugin.Maui.Audio.AudioManager.CreatePlayer(Stream audioStream)
```

```
var player = audioManager.CreatePlayer(await FileSystem.OpenAppPackageFileAsync("sound.wav"));
            player.Loop = true;
            player.Play();
}

```

What is the solution? I want to use this library.

**Comment by ertandk** [comment]
@jfversluis

**Comment by jfversluis** [comment]
Could you maybe add a reproduction project for this so I can have a look?

The error doesn't have a lot of info, but this line: `**Java.IO.IOException:** 'Prepare failed.: status=0x1'` makes me think that it either can't find the file that you specify or you didn't request the necessary permissions.

**Comment by jfversluis** [comment]
Sure, you can use `System.IO.ReadAllBytes` and turn that into a stream and use that as well, but I suspect that won't be much different.

You might want to try and move this line: `await FileSystem.OpenAppPackageFileAsync("sound.wav")` to it's own variable. So for instance: `var soundFile = await FileSystem.OpenAppPackageFileAsync("sound.wav");` then debug through it and see if that actually works.

Also double-check that you added the file in the Resources/Raw folder and the BuildAction is set the MauiAsset.

As mentioned: I have a feeling that it either can't find the file or it can't be opened due to a permissions issue.

**Comment by ertandk** [comment]
`<MauiAsset Include="Resources\Raw\**" LogicalName="%(RecursiveDir)%(Filename)%(Extension)" />`
attached,
now I tried it on different physical android 10, android 11 devices, it didn't crash.
On my old device this crashes,
`var soundFile = await FileSystem.OpenAppPackageFileAsync("sound.wav");` crashing is happening here.

https://github.com/adrianstevens/Xamarin-Plugins/issues/75#issuecomment-722036590 I seem to have the same problem as people here.

I was planning to finish the application, I was very upset when I threw it on my old device and observed this problem :(

**Comment by jfversluis** [comment]
Looks like there was also a workaround provided: https://github.com/adrianstevens/Xamarin-Plugins/issues/75#issuecomment-899456624

It seems like those device cannot handle a certain type of audio files. 

I'm afraid there is not much we can do about that with our code. This has to do with what a device supports for the audio. I hope you can figure out how to make it work, please let us know if you do!
