### ISSUE TITLE
IPhone Doesn't play the audio

### ISSUE THREAD

**Issue by techbud** [jfversluis/Plugin.Maui.Audio#55]
It seems like the audio isn't playing on iPhone, either in the simulator or on a real device. The Device is on iPhone 16.3.1 and the Simulator is on 16.4. It does play fine on Android and Windows. Not sure if it is something I'm missing or something wrong as I am new to the Plugin.

**Comment by jfversluis** [comment]
What is the code are you using? Do you have a small sample project? We have had no complaints about this so far so I suspect it has to do something with how you've set it up.

**Comment by techbud** [comment]
I have two top-level variables:
`private readonly IAudioManager audioManager;
 private IAudioPlayer player;`

Then in a function, I create the player and play it:
`var file = await Microsoft.Maui.Storage.FileSystem.OpenAppPackageFileAsync("FinalBeepSound.mp3");
 player = audioManager.CreatePlayer(file);
 player.Play();`

Then I dispose of it in two functions, either on the back press or on the user saving his work:
` player.Dispose();`

**Comment by techbud** [comment]
Alright, I think I figured out the problem, I'm implementing it in a callback of a timer. It looks like Windows and Android play the sound before it's done just fine, but iOS doesn't play in time.

**Comment by yajiegithub** [comment]
I don't know what went wrong. I ran your sample.
And I only open the mic permission on ios, but the playback has no sound, and the playback does not stop, how should I find the problem?

**Comment by yajiegithub** [comment]
> 
I don't know what went wrong. I ran your sample.
And I only open the mic permission on ios, but the playback has no sound, and the playback does not stop, how should I find the problem?

**Comment by yajiegithub** [comment]
> What is the code are you using? Do you have a small sample project? We have had no complaints about this so far so I suspect it has to do something with how you've set it up.

I don't know what went wrong. I ran your sample.
And I only open the mic permission on ios, but the playback has no sound, and the playback does not stop, how should I find the problem?
