### ISSUE TITLE
IAudioPlayer.Duration Value Difference (Android vs. Windows) 🔊

### ISSUE THREAD

**Issue by Danielkaas94** [jfversluis/Plugin.Maui.Audio#61]
While debugging my app, I notice a difference for the duration compared with Android and Windows

```csharp
var player = audioManager.CreatePlayer(await FileSystem.OpenAppPackageFileAsync("dswpnup.wav"));
var duration = player.Duration; // Just Testing

/*
   player.Duration (the length of audio in seconds)
         Android: 0.532
         Windows: 0.5328798
*/

player.Play();
```

**Comment by jfversluis** [comment]
Probably a rounding difference between platforms. Besides you spotting a difference, is there an actual problem you encounter because of this?

**Comment by Danielkaas94** [comment]
My short sounds are ending too soon, but don't worry, I have added some additional silience to my audio files

**Comment by bijington** [comment]
If they are stopping short it might be related to this issue https://github.com/jfversluis/Plugin.Maui.Audio/issues/43
