### ISSUE TITLE
Duration is in miliseconds

### ISSUE THREAD

**Issue by DiogoDeAlmeida** [jfversluis/Plugin.Maui.Audio#68]
Hi there !

In the documentation we can see duration is in seconds but it seems to be in miliseconds.

[src/Plugin.Maui.Audio/AudioPlayer/IAudioPlayer.cs](https://github.com/jfversluis/Plugin.Maui.Audio/blob/748f960b909ce45d00d19cf8d7ad15da21b60b0a/src/Plugin.Maui.Audio/AudioPlayer/IAudioPlayer.cs#L16)

**Comment by andrasjani** [comment]
on Windows it works fine (shown in seconds), on Android it doesn't...

**Comment by bijington** [comment]
Good spot! Thanks for this
