### ISSUE TITLE
IOS simple No sound,

### ISSUE THREAD

**Issue by yajiegithub** [jfversluis/Plugin.Maui.Audio#70]
I don't know what went wrong. I ran your sample.
And I only open the mic permission on ios, but the playback has no sound, and the playback does not stop, how should I find the problem?

https://github.com/jfversluis/Plugin.Maui.Audio/assets/35278902/c0453745-358a-4a2f-b04b-be6a8c979c72

**Comment by bijington** [comment]
I have only been able to test this using an iOS emulator but it worked fine here. Is your device on mute? Or are there any errors/warnings being logged in the application output/debug tab?

**Comment by yajiegithub** [comment]
> I have only been able to test this using an iOS emulator but it worked fine here. Is your device on mute? Or are there any errors/warnings being logged in the application output/debug tab?

 I found where bug is.
Normal operation after change

@AudioRecorder.macios.cs     line24
	var error = audioSession.SetCategory(AVAudioSessionCategory.Record);

change 
	var error = audioSession.SetCategory(AVAudioSessionCategory.PlayAndRecord);

AudioPlayer has bug too,
1: Close app frequently.
2:Occasionally there is no sound.

**Comment by tomShoutTheSecond** [comment]
For me, audio playback is silent on iPhone Device, but using iPhone Simulator, the playback is heard

**Comment by jfversluis** [comment]
@tomShoutTheSecond on the physical device is the silent switch on the side on?

**Comment by jfversluis** [comment]
If only people would read [the docs](https://github.com/jfversluis/Plugin.Maui.Audio/wiki#how-to-make-the-audio-play-even-though-the-hardware-silentmute-switch-is-toggled) 🤪 yeah we need some good way to figure this out for sure.

**Comment by benjfirefly** [comment]
> If only people would read [the docs](https://github.com/jfversluis/Plugin.Maui.Audio/wiki#how-to-make-the-audio-play-even-though-the-hardware-silentmute-switch-is-toggled) 🤪 yeah we need some good way to figure this out for sure.

Agreed (guiltily on both counts :/) I can't think of a reason you'd want playback to obey silent mode by default (none of the other audio-based apps on my device seem to) but if you don't want to implement this as standard, reporting a failure would sure help. As it stands, when silent is enabled, the Play command runs without error and the PlaybackEnded callback will never fire :(

**Comment by tomShoutTheSecond** [comment]
> Hm yeah the option might be something. Or just have a bit ugly, but functional property: `IgnoreAppleSilentSwitch`?

This would be ideal, thanks!

**Comment by bijington** [comment]
> Hm yeah the option might be something. Or just have a bit ugly, but functional property: `IgnoreAppleSilentSwitch`? 

My fear there is that it might not fit all use cases. [`AVAudioSessionCategory`](https://developer.apple.com/documentation/avfaudio/avaudiosessioncategory#3432377) has quite a few options that offer different functionality. I was wondering whether we could allow the developer to define this. Potentially different options for playback vs record. What do you think?
