### ISSUE TITLE
NullReferenceException when loading sound using android asset name

### ISSUE THREAD

**Issue by RonnyBansemer** [jfversluis/Plugin.Maui.Audio#81]
[This line](https://github.com/jfversluis/Plugin.Maui.Audio/blob/main/src/Plugin.Maui.Audio/AudioPlayer/AudioPlayer.android.cs#L98C7-L98C7) causes an NullReferenceException on android when trying to load an asset sound. `player` is not set but referenced when accessing `Loop`

![image](https://github.com/jfversluis/Plugin.Maui.Audio/assets/45567951/74ead059-70c9-44c2-aba3-2e6949f91e34)

**Comment by bijington** [comment]
Good spot! No clue how we missed this one
