### ISSUE TITLE
In .Net 8 MAUI When CreatePlayer Display error

### ISSUE THREAD

**Issue by chenludaniel** [jfversluis/Plugin.Maui.Audio#83]
error message: Could not find a part of the path '/data/data/xxx/files/Documents/cache0.wav

**Comment by bijington** [comment]
I think we fixed that as part of this issue: https://github.com/jfversluis/Plugin.Maui.Audio/issues/74

@jfversluis do you think we could release a new version with the current fixes in it?

**Comment by chenludaniel** [comment]
> I think we fixed that as part of this issue: #74
> 
> @jfversluis do you think we could release a new version with the current fixes in it?

I downloaded the code and applied the project Plugin.Maui.Audio, and then found that it was executed correctly. Both Android 5 and Android 11 can run normally。I think you can release the latest version

**Comment by jfversluis** [comment]
Issues a new pre-release of v3.0 with this fix: https://github.com/jfversluis/Plugin.Maui.Audio/releases/tag/v3.0.0-preview2

Should be available in a few minutes. If we don't hear any weird things about v3 in the upcoming days, I'll release it as a stable version next week.
