### ISSUE TITLE
Playback fails on IOS devices when any audioRecorder is created

### ISSUE THREAD

**Issue by JamesBodi** [jfversluis/Plugin.Maui.Audio#91]
Playback of wav and mp3 files works on IOS simulators and devices, until you try to record a new audio.

As soon as this line is executed playback no longer works:

`     _audioRecorder = _audioManager.CreateRecorder();`

It doesn't matter if I go on to actually record audio, creating the recorder is enough to cause playback to fail. I can record new audio files, but they won't playback. At least not until I restart the app, at which point everything will playback including the new audio file.

MediaElement has an almost identical issue which I have already documented here:
https://github.com/CommunityToolkit/Maui/issues/1634#issuecomment-1876153420

Please see test project ReadMe for more details:
https://github.com/JamesBodi/MauiPluginAudioTestApp.git

**Comment by JamesBodi** [comment]
I have continued to research this and eventually just wrote my own audio service in native code. In the process **I think I discovered why MediaElement and Plugin.Maui.Audio fail when attempting to playback on any IOS device**.

If your code looks like this it **won't** work:

```
        public void PlayAudio(string filePath)
        {
            if (_player == null)
            {
                _url = NSUrl.FromString(filePath); //  <<
                AVPlayerItem avPlayerItem = new AVPlayerItem(_url); //  <<
                _player = new AVPlayer(avPlayerItem);
                _player.AutomaticallyWaitsToMinimizeStalling = false;
                _player.Volume = 1;
                _player.Play();
...
```
But if your code looks like this it **will** work:

```
        public void PlayAudio(string filePath)
        {
            if (_player == null)
            {
                AVAsset asset = AVAsset.FromUrl(NSUrl.CreateFileUrl(new[] { filePath }));  // <<
                AVPlayerItem avPlayerItem = new AVPlayerItem(asset);  // <<
                _player = new AVPlayer(avPlayerItem);
                _player.AutomaticallyWaitsToMinimizeStalling = false;
                _player.Volume = 1;
                _player.Play();
...
```

I am guessing that MediaElement and Plugin.Maui.Audio are using the same base code as they both fail in the same way and have the same author. As my native code audio service is working perfectly I will not be switching back.

**Comment by borrmann** [comment]
@jfversluis has anyone looked into this? Even using the sample app from this Plugin.Maui.Audio, I am unable to play a recording on iOS.

Attached a screen video: 
1. Recording seems to work fine
2. Clicking on Play, the "Ca

https://github.com/jfversluis/Plugin.Maui.Audio/assets/20472867/2ed4c6c1-3327-4fb3-98f7-25c7f472d548

nExecute" of the buttons updates, but the timer stands still and no sound appears (Device was on loud and max volume)

**Comment by borrmann** [comment]
Maybe it behaves differently due to different states of [avaudiosession](https://developer.apple.com/documentation/avfaudio/avaudiosession)  ?

**Comment by borrmann** [comment]
@bijington 
the following works:

before playing:
``` 
AVAudioSession.SharedInstance().SetCategory(AVAudioSessionCategory.Playback, AVAudioSessionCategoryOptions.DefaultToSpeaker); 
AVAudioSession.SharedInstance().SetActive(true);
```

and 
``` 
AVAudioSession.SharedInstance().SetCategory(AVAudioSessionCategory.Record, options: AVAudioSessionCategoryOptions.DefaultToSpeaker);
AVAudioSession.SharedInstance().SetActive(true);
```
before recording 

I guess there is a lot more to it since AVAudioSessionCategoryOptions has a lot of options and so does AVAudioSessionCategory, including the PlayAndRecord, which I guess should also work. It could also be considered to invoke `AVAudioSession.SharedInstance().SetActive(false, AVAudioSessionSetActiveOptions.NotifyOthersOnDeactivation); `
in any Stop or Pause methods

**Comment by borrmann** [comment]
@bijington I have created a Pull Request that fixes this issue and adds support for BitDepth, SampleRate, Channels, and some options for Encodings as well, as well as some other fixes for the sample app.

**Comment by kevinjohnobrien** [comment]
I am experiencing the same issue when recording then trying to play.

The issue it seems is related to the use of `AVAudioSessionCategory.Record`.

As mentioned in https://developer.apple.com/documentation/avfaudio/avaudiosessioncategoryrecord ...
_This category has the effect of silencing virtually all output on the system, for as long as the session is active. Unless you need to prevent any unexpected sounds from being played, use [AVAudioSessionCategoryPlayAndRecord] instead._

I have tested this by updating the Plugin.Maui.Audio code locally, replacing `AVAudioSessionCategory.Record` with `AVAudioSessionCategory.PlayAndRecord` in "AudioRecorder.macios.cs" which resulted in recording and playing working successfully together.

As an aside, I'd like to say a big thanks for developing this plugin in the first place.
