### ISSUE TITLE
Can this library record windows speaker audio ?

### ISSUE THREAD

**Issue by KANDURISHOURI** [jfversluis/Plugin.Maui.Audio#92]
I am trying to create a Windows application to record speaker and microphone audio using .NET MAUI. Is there any way to do this? Currently, I can record microphone audio using this library. 
Any information on how to record speaker audio too, using this library would be helpful.

**Comment by jfversluis** [comment]
We currently don't have any plans to record the system sound, just from the microphone. Thanks!
