### ISSUE TITLE
Volume Increase/Decrease/Mute/Unmute

### ISSUE THREAD

**Issue by Shahid-khan5** [jfversluis/Plugin.Maui.Audio#93]
How I can increase/decrease or mute/unmute volume?

**Comment by jfversluis** [comment]
There is a `Volume` property that you can use for this. For muting/unmuting, make sure you make note of the current value for the volume, then set it to 0 to mute and restore it to the previous value to unmute.

**Comment by Shahid-khan5** [comment]
Thanks. It is in the Audio Player class, I was looking into it in the AudioManager Class.
