### ISSUE TITLE
Retrieving files from recordings

### ISSUE THREAD

**Issue by borrmann** [jfversluis/Plugin.Maui.Audio#98]
I am probably missing something here, but can't get quite behind it.
The md file of the audio recording says, 

"_You as the developer are responsible for cleaning up the audio files. For instance, when using StartAsync() the random file that is generated is not cleaned up automatically. Retrieve the file path which is in the resulting object from StopAsync() and use that to remove the file when done._"

StopAsync(), returns IAudioSource. The only public API of IAudioSource is `Stream GetAudioStream();` . How do I get the file? Am I missing something?

EDIT:
it looks like the actual implementation does return the FilePath wit `GetFilePath()`, but the interface does not declare it

**Comment by jfversluis** [comment]
Cast it to [`FileAudioSource`](https://github.com/jfversluis/Plugin.Maui.Audio/blob/main/src/Plugin.Maui.Audio/FileAudioSource.cs) and you will have more options including retrieving the file path!
